# Generated by Django 5.0.5 on 2024-08-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("cover_image", models.ImageField(upload_to="Image")),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("ratings_count", models.IntegerField(default=0)),
            ],
        ),
    ]
