# Generated by Django 5.0.5 on 2024-08-09 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_recommendation_comment_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
    ]
